import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { getServerSession } from "next-auth";
import SessionProvider from "@/app/providers/session-provider";
import { ToastProvider } from "@/app/providers/toast-provider";
import Navbar from "./components/navbar";
import QueryClientProvider from "./providers/query-client-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kvey Store",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <QueryClientProvider>
            <Navbar />
            <main className="mt-16 h-auto">{children}</main>
            <ToastProvider />
          </QueryClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
